from app.translator.core.models.platform_details import PlatformDetails


DEFAULT_SUMOLOGIC_CSE_RULE = {
    "name": "Autogenerated Sumo Logic CSE Rule",
    "description": "Autogenerated Sumo Logic CSE Rule",
    "enabled": True,
    "expression": "",
    "assetField": "device_hostname",
    "score": 3,
    "stream": "record",
    "category": "Unknown/Other"
}


PLATFORM_DETAILS = {"group_id": "sumologic", "group_name": "SumoLogic", "first_choice": 0}


SUMOLOGIC_SEARCH_QUERY_DETAILS = {
    "platform_id": "sumologic-search-query",
    "name": "Sumo Logic",
    "platform_name": "Query",
    **PLATFORM_DETAILS
}

SUMOLOGIC_CSE_QUERY_DETAILS = {
    "platform_id": "sumologic-cse-query",
    "name": "Sumo Logic CSE",
    "platform_name": "CSE Query",
    **PLATFORM_DETAILS
}

SUMOLOGIC_CSE_RULE_DETAILS = {
    "platform_id": "sumologic-cse-rule",
    "name": "Sumo Logic CSE Rule",
    "platform_name": "CSE Rule",
    **PLATFORM_DETAILS
}

SEVERITY_MAP = {
    'informational': 1,
    'low': 2,
    'medium': 3,
    'high': 4,
    'critical': 5
}

ALLOWED_CATEGORIES = [
    "Threat Intelligence",
    "Initial Access",
    "Execution",
    "Persistence",
    "Privilege Escalation",
    "Defense Evasion",
    "Credential Access",
    "Discovery",
    "Lateral Movement",
    "Collection",
    "Command and Control",
    "Exfiltration",
    "Impact"
]



sumologic_search_query_details = PlatformDetails(**SUMOLOGIC_SEARCH_QUERY_DETAILS)
sumologic_cse_query_details = PlatformDetails(**SUMOLOGIC_CSE_QUERY_DETAILS)
sumologic_cse_rule_details = PlatformDetails(**SUMOLOGIC_CSE_RULE_DETAILS)
