from app.translator.core.custom_types.meta_info import SeverityType
from app.translator.core.models.platform_details import PlatformDetails

DEFAULT_MICROSOFT_SENTINEL_RULE = {
    "displayName": "Autogenerated Microsoft Sentinel Rule",
    "description": "Autogenerated Microsoft Sentinel Rule",
    "severity": SeverityType.medium,
    "enabled": True,
    "query": "",
    "queryFrequency": "PT30M",
    "queryPeriod": "PT30M",
    "triggerOperator": "GreaterThan",
    "triggerThreshold": 0,
    "suppressionDuration": "PT2H30M",
    "suppressionEnabled": True,
    "tactics": [],
    "techniques": [],
}

PLATFORM_DETAILS = {"group_id": "sentinel", "group_name": "Microsoft Sentinel"}

_SENTINEL_KQL_QUERY = "sentinel-kql-query"
_SENTINEL_KQL_RULE = "sentinel-kql-rule"

MICROSOFT_SENTINEL_QUERY_DETAILS = {
    "platform_id": _SENTINEL_KQL_QUERY,
    "name": "Microsoft Sentinel Query",
    "platform_name": "Query (Kusto)",
    **PLATFORM_DETAILS,
}

MICROSOFT_SENTINEL_RULE_DETAILS = {
    "platform_id": _SENTINEL_KQL_RULE,
    "name": "Microsoft Sentinel Rule",
    "platform_name": "Rule (Kusto)",
    "first_choice": 0,
    **PLATFORM_DETAILS,
}

MICROSOFT_SENTINEL_YAML_RULE_DETAILS = {
    "platform_id": "sentinel-kql-yaml-rule",
    "name": "Microsoft Sentinel YAML Rule",
    "platform_name": "YAML Rule (Kusto)",
    "first_choice": 0,
    **PLATFORM_DETAILS,
}

MICROSOFT_DEFENDER_DETAILS = {
    "platform_id": "mde-kql-query",
    "group_name": "Microsoft Defender for Endpoint",
    "name": "Microsoft Defender for Endpoint",
    "platform_name": "Query (Kusto)",
    "group_id": "microsoft-defender",
}


DEFAULT_MICROSOFT_DEFENDER_CTI_MAPPING = {
    "DestinationIP": "RemoteIP",
    "SourceIP": "LocalIP",
    "HashSha256": "InitiatingProcessSHA256",
    "HashMd5": "InitiatingProcessMD5",
    "Emails": "SenderFromAddress",
    "Domain": "RemoteUrl",
    "HashSha1": "InitiatingProcessSHA1",
    "Files": "FileName",
    "URL": "RemoteUrl",
}

DEFAULT_MICROSOFT_SENTINEL_CTI_MAPPING = {
    "DestinationIP": "DestinationIp",
    "SourceIP": "SourceIp",
    "HashSha512": "FileHashSha512",
    "HashSha256": "FileHashSha256",
    "HashMd5": "FileHashMd5",
    "Emails": "SenderFromAddress",
    "Domain": "DestinationHostname",
    "HashSha1": "FileHashSha1",
    "Files": "TargetFileName",
    "URL": "URL",
}


MICROSOFT_SENTINEL_QUERY_TYPES = {_SENTINEL_KQL_QUERY, _SENTINEL_KQL_RULE}

microsoft_defender_query_details = PlatformDetails(**MICROSOFT_DEFENDER_DETAILS)
microsoft_sentinel_query_details = PlatformDetails(**MICROSOFT_SENTINEL_QUERY_DETAILS)
microsoft_sentinel_rule_details = PlatformDetails(**MICROSOFT_SENTINEL_RULE_DETAILS)
microsoft_sentinel_yaml_rule_details = PlatformDetails(**MICROSOFT_SENTINEL_YAML_RULE_DETAILS)
