from app.translator.core.models.platform_details import PlatformDetails

DEFAULT_SUMOLOGIC_CSE_RULE = {
    "name": "Autogenerated Sumo Logic CSE Rule",
    "description": "Autogenerated Sumo Logic CSE Rule",
    "enabled": True,
    "expression": "",
    "assetField": "device_hostname",
    "score": 3,
    "stream": "record",
    "category": "Unknown/Other"
}


SUMO_LOGIC_QUERY_DETAILS = {
    "siem_type": "sumologic-search-query",
    "name": "Sumo Logic Query",
    "group_name": "Sumo Logic",
    "platform_name": "Query",
    "group_id": "sumologic-search-query"
}

SUMO_LOGIC_CSE_DETAILS = {
    "siem_type": "sumologic-cse-query",
    "name": "Sumo Logic CSE",
    "group_name": "Sumo Logic",
    "platform_name": "Query",
    "group_id": "sumologic-cse-query"
}

SUMO_LOGIC_CSE_RULE_DETAILS = {
    "siem_type": "sumologic-cse-rule",
    "name": "Sumo Logic CSE Rule",
    "group_name": "Sumo Logic",
    "platform_name": "Rule",
    "group_id": "sumologic-cse-rule"
}

SEVERITY_MAP = {
    'informational': 1,
    'low': 2,
    'medium': 3,
    'high': 4,
    'critical': 5
}

ALLOWED_CATEGORIES = [
    "Threat Intelligence",
    "Initial Access",
    "Execution",
    "Persistence",
    "Privilege Escalation",
    "Defense Evasion",
    "Credential Access",
    "Discovery",
    "Lateral Movement",
    "Collection",
    "Command and Control",
    "Exfiltration",
    "Impact"
]

sumologic_query_details = PlatformDetails(**SUMO_LOGIC_QUERY_DETAILS)
sumologic_cse_details = PlatformDetails(**SUMO_LOGIC_CSE_DETAILS)
sumologic_cse_rule_details = PlatformDetails(**SUMO_LOGIC_CSE_RULE_DETAILS)
